Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/jupyter_cache/executors/utils.py", line 56, in single_nb_execution
    record_timing=False,
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/nbclient/client.py", line 1093, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
    return future.result()
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/nbclient/client.py", line 560, in async_execute
    cell, index, execution_count=self.code_cells_executed + 1
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/nbclient/client.py", line 854, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/nbclient/client.py", line 756, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
def get_parametros_regressao_linear(x: pd.Series, y: pd.Series) -> tuple[np.number, np.number]:
    media_x: np.number = x.mean()
    media_y: np.number = y.mean()
    diff_x_media_x: pd.Series = x - media_x

    beta_um: np.number = (diff_x_media_x * y).sum() / (diff_x_media_x ** 2).sum()
    beta_zero: np.number = media_y - beta_um * media_x
    
    return (beta_zero, beta_um)

def get_variancia_dos_parametros(x: pd.Series, y: pd.Series, beta_zero: np.number, beta_um: np.number) -> tuple[np.number, np.number]:
    n = len(y)
    media_x = x.mean()
    soma_diff_x_media_x_quadrado: pd.Series = ((x - media_x) ** 2).sum()
    y_estimado: pd.Series = beta_zero - beta_um * x
    sigma_quadrado = ((y - y_estimado) ** 2).sum() / (n - 2)

    variancia_beta_um: np.number = sigma_quadrado / soma_diff_x_media_x_quadrado
    variancia_beta_zero: np.number = sigma_quadrado * ( (1/n) + (( media_x ** 2 ) / (soma_diff_x_media_x_quadrado)) )

    return (variancia_beta_zero, variancia_beta_um)

def get_estatisticas_de_teste_t(parametro: np.number, variancia_parametro: np.number) -> np.number:
    return parametro / np.sqrt(variancia_parametro)

def get_pvalor(estatistica_de_teste_t: np.number) -> np.number:
    return 2 * scypy_stats.t.cdf(estatistica_de_teste_t)
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mTypeError[0m                                 Traceback (most recent call last)
[0;32m/tmp/ipykernel_17599/706325833.py[0m in [0;36m<module>[0;34m[0m
[0;32m----> 1[0;31m [0;32mdef[0m [0mget_parametros_regressao_linear[0m[0;34m([0m[0mx[0m[0;34m:[0m [0mpd[0m[0;34m.[0m[0mSeries[0m[0;34m,[0m [0my[0m[0;34m:[0m [0mpd[0m[0;34m.[0m[0mSeries[0m[0;34m)[0m [0;34m->[0m [0mtuple[0m[0;34m[[0m[0mnp[0m[0;34m.[0m[0mnumber[0m[0;34m,[0m [0mnp[0m[0;34m.[0m[0mnumber[0m[0;34m][0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      2[0m     [0mmedia_x[0m[0;34m:[0m [0mnp[0m[0;34m.[0m[0mnumber[0m [0;34m=[0m [0mx[0m[0;34m.[0m[0mmean[0m[0;34m([0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m      3[0m     [0mmedia_y[0m[0;34m:[0m [0mnp[0m[0;34m.[0m[0mnumber[0m [0;34m=[0m [0my[0m[0;34m.[0m[0mmean[0m[0;34m([0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m      4[0m     [0mdiff_x_media_x[0m[0;34m:[0m [0mpd[0m[0;34m.[0m[0mSeries[0m [0;34m=[0m [0mx[0m [0;34m-[0m [0mmedia_x[0m[0;34m[0m[0;34m[0m[0m
[1;32m      5[0m [0;34m[0m[0m

[0;31mTypeError[0m: 'type' object is not subscriptable
TypeError: 'type' object is not subscriptable

